# Updated docker-compose.yml with review processing support and PhoneBridge

version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./logs:/app/logs  # Add logs volume
      - ~/.modal:/root/.modal
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=true
      - REVIEW_CRON_INTERVAL=5  # 5 minutes for development
      - MODAL_APP_NAME=hotel-review-analyzer
      - ADMIN_EMAIL=markminj@gmail.com
      - MODAL_TOKEN_ID=ak-fdhXPa5QN7rTubEptCrdNM
      - MODAL_TOKEN_SECRET=as-a5JTMFiiCoX93DYjhyIUgP
      - MODAL_ENVIRONMENT=${MODAL_ENVIRONMENT:-main}
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      # PhoneBridge Environment Variables (NEW)
      - ZOHO_CLIENT_ID=${ZOHO_CLIENT_ID}
      - ZOHO_CLIENT_SECRET=${ZOHO_CLIENT_SECRET}
      - ZOHO_REDIRECT_URI=${ZOHO_REDIRECT_URI}
      - VITALPBX_API_BASE=https://cc.fusionsystems.co.ke/api
      - VITALPBX_USERNAME=${VITALPBX_USERNAME}
      - VITALPBX_PASSWORD=${VITALPBX_PASSWORD}
      - VITALPBX_API_KEY=${VITALPBX_API_KEY}
      - CALL_TIMEOUT=30
      - PHONEBRIDGE_MAX_RETRIES=3
      - POPUP_ENABLED=true
      - POPUP_TIMEOUT_SECONDS=10
      - CONTACT_LOOKUP_CACHE_TTL=300
      - MAX_POPUP_RETRIES=3
      - INCLUDE_CALL_HISTORY=true
      - INCLUDE_RECENT_NOTES=true

      # NEW: PhoneBridge API Configuration
      - PHONEBRIDGE_API_URL=https://www.zohoapis.com/phonebridge/v3
      - PHONEBRIDGE_POPUP_ENDPOINT=/calls/popup
      - PHONEBRIDGE_CONTROL_ENDPOINT=/calls/control

      # NEW: Performance Settings
      - MAX_CONCURRENT_POPUPS=50
      - POPUP_RETRY_DELAY=60
      - CALL_LOG_RETENTION_DAYS=90

      # NEW: Phone Number Settings
      - DEFAULT_COUNTRY_CODE=kenya
    depends_on:
      - db
      - redis
    user: root  # Temporary for debugging Modal issues

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # Cron job service for review processing
  review-processor:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app
      - ./logs:/app/logs
      - ~/.modal:/root/.modal
    command: >
      sh -c "python manage.py wait_for_db &&
             while true; do
               python manage.py process_reviews --batch-size=20;
               sleep 300;
             done"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb 
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=true
      - REVIEW_CRON_INTERVAL=5
      - MODAL_APP_NAME=hotel-review-analyzer
      - ADMIN_EMAIL=markminj@gmail.com
      - MODAL_TOKEN_ID=ak-fdhXPa5QN7rTubEptCrdNM
      - MODAL_TOKEN_SECRET=as-a5JTMFiiCoX93DYjhyIUgP
      - MODAL_ENVIRONMENT=${MODAL_ENVIRONMENT:-main}
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    depends_on:
      - db
      - redis
    restart: unless-stopped
    user: root  # Temporary for debugging Modal issues

volumes:
  dev-db-data:
  redis-data:
  logs: