# Generated by Django 4.0.10 on 2025-08-05 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(help_text='VitalPBX call ID for quick lookup', max_length=100)),
                ('zoho_user_id', models.CharField(help_text='Target Zoho user ID', max_length=100)),
                ('extension', models.CharField(help_text='Extension that received/made the call', max_length=20)),
                ('popup_data', models.JSONField(help_text='Complete popup data sent to Zoho PhoneBridge API')),
                ('popup_sent_at', models.DateTimeField(auto_now_add=True)),
                ('zoho_response', models.TextField(blank=True, help_text='Raw response from Zoho PhoneBridge API')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent Successfully'), ('failed', 'Failed'), ('retry', 'Retry Required'), ('duplicate', 'Duplicate Prevented')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if popup failed')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='API response time in milliseconds', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
            ],
            options={
                'ordering': ['-popup_sent_at'],
            },
        ),
        migrations.AddField(
            model_name='calllog',
            name='call_history_count',
            field=models.IntegerField(default=0, help_text='Number of previous calls with this contact'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='call_state',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('connected', 'Connected'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy')], default='initiated', help_text='Current call state based on VitalPBX events', max_length=20),
        ),
        migrations.AddField(
            model_name='calllog',
            name='contact_company',
            field=models.CharField(blank=True, help_text='Company name from CRM', max_length=255),
        ),
        migrations.AddField(
            model_name='calllog',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email from CRM record', max_length=254),
        ),
        migrations.AddField(
            model_name='calllog',
            name='contact_id',
            field=models.CharField(blank=True, help_text='Zoho CRM Contact/Lead ID', max_length=100),
        ),
        migrations.AddField(
            model_name='calllog',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Contact/Lead name from CRM', max_length=255),
        ),
        migrations.AddField(
            model_name='calllog',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('contact', 'Contact'), ('lead', 'Lead'), ('unknown', 'Unknown')], help_text='Type of CRM record found', max_length=20),
        ),
        migrations.AddField(
            model_name='calllog',
            name='normalized_phone',
            field=models.CharField(blank=True, help_text='Normalized phone number (+254 format)', max_length=20),
        ),
        migrations.AddField(
            model_name='calllog',
            name='popup_response',
            field=models.TextField(blank=True, help_text='Response from Zoho PhoneBridge API'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='popup_sent',
            field=models.BooleanField(default=False, help_text='Whether popup was sent to Zoho PhoneBridge'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='recent_activity',
            field=models.TextField(blank=True, help_text='Recent CRM activity/notes for popup display'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['call_id'], name='phonebridge_call_id_c3c8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['normalized_phone'], name='phonebridge_normali_180c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['contact_id'], name='phonebridge_contact_299420_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['extension', 'start_time'], name='phonebridge_extensi_f7cfb7_idx'),
        ),
        migrations.AddField(
            model_name='popuplog',
            name='call_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup_logs', to='phonebridge.calllog'),
        ),
        migrations.AddIndex(
            model_name='popuplog',
            index=models.Index(fields=['call_id'], name='phonebridge_call_id_76d5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='popuplog',
            index=models.Index(fields=['zoho_user_id'], name='phonebridge_zoho_us_9f2833_idx'),
        ),
        migrations.AddIndex(
            model_name='popuplog',
            index=models.Index(fields=['extension'], name='phonebridge_extensi_c8830a_idx'),
        ),
        migrations.AddIndex(
            model_name='popuplog',
            index=models.Index(fields=['status'], name='phonebridge_status_376d6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='popuplog',
            unique_together={('call_id', 'zoho_user_id')},
        ),
    ]
