# Generated by Django 4.0.10 on 2025-08-07 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phonebridge', '0002_popuplog_calllog_call_history_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthMigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_token_data', models.JSONField(blank=True, help_text='Backup of old token data', null=True)),
                ('migration_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('migration_started_at', models.DateTimeField(auto_now_add=True)),
                ('migration_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Migration notes and details')),
            ],
            options={
                'ordering': ['-migration_started_at'],
            },
        ),
        migrations.AddField(
            model_name='zohotoken',
            name='api_domain',
            field=models.URLField(blank=True, help_text='Location-specific API domain (e.g., https://www.zohoapis.com)'),
        ),
        migrations.AddField(
            model_name='zohotoken',
            name='last_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zohotoken',
            name='location',
            field=models.CharField(blank=True, help_text='Zoho location (us, eu, in, au, jp, sa, ca)', max_length=10),
        ),
        migrations.AddField(
            model_name='zohotoken',
            name='oauth_domain',
            field=models.URLField(blank=True, help_text='Location-specific OAuth domain (e.g., https://accounts.zoho.com)'),
        ),
        migrations.AddField(
            model_name='zohotoken',
            name='oauth_version',
            field=models.CharField(default='v3', help_text='OAuth version used (v2 for legacy, v3 for new PhoneBridge)', max_length=10),
        ),
        migrations.AddField(
            model_name='zohotoken',
            name='scopes_granted',
            field=models.TextField(blank=True, help_text='Comma-separated list of granted scopes'),
        ),
        migrations.AddField(
            model_name='zohotoken',
            name='token_type',
            field=models.CharField(default='Bearer', help_text='Token type from OAuth response', max_length=20),
        ),
        migrations.AddIndex(
            model_name='zohotoken',
            index=models.Index(fields=['expires_at'], name='phonebridge_expires_e5641d_idx'),
        ),
        migrations.AddIndex(
            model_name='zohotoken',
            index=models.Index(fields=['location'], name='phonebridge_locatio_b827b0_idx'),
        ),
        migrations.AddIndex(
            model_name='zohotoken',
            index=models.Index(fields=['oauth_version'], name='phonebridge_oauth_v_ff131e_idx'),
        ),
        migrations.AddField(
            model_name='oauthmigrationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
