# Generated by Django 4.0.10 on 2025-05-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsComputationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computation_date', models.DateTimeField(auto_now_add=True, help_text='When the computation ran')),
                ('hotels_processed', models.IntegerField(default=0, help_text='Number of hotels processed')),
                ('snapshots_created', models.IntegerField(default=0, help_text='Number of snapshots created')),
                ('snapshots_updated', models.IntegerField(default=0, help_text='Number of snapshots updated')),
                ('processing_time_seconds', models.FloatField(blank=True, help_text='Total processing time', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed')),
            ],
            options={
                'ordering': ['-computation_date'],
            },
        ),
        migrations.CreateModel(
            name='HotelAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(help_text='Hotel identifier', max_length=100)),
                ('hotel_name', models.CharField(help_text='Hotel name for quick reference', max_length=255)),
                ('snapshot_date', models.DateField(help_text='Date this snapshot represents')),
                ('granularity', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='Time granularity of this snapshot', max_length=10)),
                ('review_count', models.IntegerField(default=0, help_text='Total reviews for this time period')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average rating for this period', max_digits=3, null=True)),
                ('sentiment_distribution', models.JSONField(default=dict, help_text='Sentiment analysis distribution')),
                ('topic_distribution', models.JSONField(default=dict, help_text='Topic analysis distribution')),
                ('rating_distribution', models.JSONField(default=dict, help_text='Distribution of 1-5 star ratings')),
                ('computed_at', models.DateTimeField(auto_now_add=True, help_text='When this snapshot was computed')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewVolumeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(help_text='Hotel identifier', max_length=100)),
                ('hotel_name', models.CharField(help_text='Hotel name for quick reference', max_length=255)),
                ('this_month_total', models.IntegerField(default=0, help_text='Total reviews this month')),
                ('this_month_daily_data', models.JSONField(default=list, help_text='Daily review counts for last 7 days')),
                ('this_month_growth', models.DecimalField(blank=True, decimal_places=2, help_text='Growth percentage vs last month', max_digits=5, null=True)),
                ('all_time_total', models.IntegerField(default=0, help_text='Total reviews all time')),
                ('all_time_monthly_data', models.JSONField(default=list, help_text='Monthly review counts for last 7 months')),
                ('all_time_growth', models.DecimalField(blank=True, decimal_places=2, help_text='Growth percentage vs previous 7 months', max_digits=5, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True, help_text='When this was computed')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
            ],
        ),
        migrations.AddIndex(
            model_name='reviewvolumestats',
            index=models.Index(fields=['hotel_id'], name='reviews_rev_hotel_i_ce294c_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewvolumestats',
            index=models.Index(fields=['computed_at'], name='reviews_rev_compute_c07e7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewvolumestats',
            unique_together={('hotel_id',)},
        ),
        migrations.AddIndex(
            model_name='hotelanalyticssnapshot',
            index=models.Index(fields=['hotel_id', 'granularity', 'snapshot_date'], name='reviews_hot_hotel_i_845346_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelanalyticssnapshot',
            index=models.Index(fields=['hotel_id', 'snapshot_date'], name='reviews_hot_hotel_i_ae09a1_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelanalyticssnapshot',
            index=models.Index(fields=['computed_at'], name='reviews_hot_compute_5d8aae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hotelanalyticssnapshot',
            unique_together={('hotel_id', 'snapshot_date', 'granularity')},
        ),
        migrations.AddIndex(
            model_name='analyticscomputationlog',
            index=models.Index(fields=['computation_date'], name='reviews_ana_computa_fae987_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticscomputationlog',
            index=models.Index(fields=['status'], name='reviews_ana_status_9b9144_idx'),
        ),
    ]
