# Generated by Django 4.0.10 on 2024-09-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recepie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepie',
            new_name='Recipe',
        ),
    ]
